import type { Metadata } from "next";
import "./globals.css";

import { poppins } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased relative bg-[#0f1515] text-white`}
      >
        <div className="grain-blur background-base" />
        <div className="grain-background background-base" />
        <div className="grid-bg background-base" />
        <div className="large-blur background-base" />
        <div className="small-blur background-base" />

        {children}
      </body>
    </html>
  );
}
